# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TheCoolVision - Grocy Tablet Interaction
version: "0.0.0"
slug: thecoolvision
description: Visualize your Grocy list on a tablet and interact with it.
url: "https://github.com/FelixMarschall/HA_GrocyTablet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/felixmarschall/thecoolvision-{arch}-addon"
