# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TheCoolVision - Grocy Tablet Interaction
version: "0.0.2"
slug: thecoolvision
description: Visualize your Grocy list on a tablet and interact with it.
url: "https://github.com/FelixMarschall/HA_GrocyTablet"
arch:
  # - armhf
  # - armv7
  # - aarch64
  - amd64
  # - i386
init: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: This is the port the web interface will be available on - for the tablet.
webui: "[PROTO:option_name]://[HOST]:[PORT:5000]"
options:
  grocy:
    url: "[PROTO:option_name]://[HOST]:[PORT:5000]"
    api_key: "xxxx"
schema:
  grocy:
    url: str?
    api_key: password
image: "ghcr.io/felixmarschall/thecoolvision-{arch}-addon"
