# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TheCoolVision - Grocy Tablet Interaction
version: "0.0.0"
slug: thecoolvision
description: Visualize your Grocy list on a tablet and interact with it.
url: "https://github.com/FelixMarschall/HA_GrocyTablet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8050/tcp: 8050
ports_description:
  8050/tcp: Web interface
webui: "[PROTO:option_name]://[HOST]:[PORT:8050]"
options:
  grocy_url: "[PROTO:option_name]://[HOST]"
  grocy_api_key: ""
schema:
  grocy_api_key: password
schema:
  message: "str?"
image: "ghcr.io/felixmarschall/thecoolvision-{arch}-addon"
